<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class Config extends Member_Controller {
	/**
	 * Model
	 * @var string
	 */
	public $model_name  = 'config_model';
	/**
	 * 
	 * @var Config_Model
	 */
	public $model;
	
	

	/**
	 * Config controller 
	 */
	
	//form add
	protected $before_add = array();
	
	//form edit
	protected $before_edit = array();
	protected $after_edit = array();
	
	//action insert
	protected $before_insert = array('before_insert');
	protected $after_insert = array();
	
	//action update
	protected $before_update = array('before_insert');
	protected $after_update = array();
	
	//form view
	protected $before_view = array();	
	protected $after_view = array();
	
    public function __construct(){
        parent::__construct();  
        
    }
    

    protected  function before_insert(){
        $aryData = array('ok'=>true);

        if(is_array($this->postData['configValue'])){

            $this->postData['configValue'] = json_encode($this->postData['configValue']);
        }
        return $aryData;
    }
    /**
	 * Build a Condition where for search 
	 * @return mixed:
	*/
    protected function _buildCondition(){
    	$aryCondition = array('visible'=>ACTIVE);
    	
    	if(!empty($this->postData)){
    		 //search
			 			
			if($this->postData['configName']!=''){
    		 	$aryCondition['like'][] =  array("configName"=>trim($this->postData['configName']));
    		 }			
			if($this->postData['configCode']!=''){
    		 	$aryCondition['like'][] =  array("configCode"=>trim($this->postData['configCode']));
    		 }			
			if($this->postData['configValue']!=''){
    		 	$aryCondition['like'][] =  array("configValue"=>$this->postData['configValue']);
    		 }
    	}
    	return $aryCondition;
    }
    
    
	/**
	 * Get data for List screen
	 * @param array $aryCondition
	 * @param int $start
	 * @return mixed
	*/ 
    protected function _getDataList($aryCondition=array(),$start='',$sort= array()){
		$rows=  parent::_getDataList($aryCondition,$start,$sort,array('select'=>'mt.*','created'=>true));
		$rows=$this->mergeGetList($rows);
		return $rows;
    }


    public function  viewConfig($id){
        $config = $this->model->get($id);
        $this->template->set('fillData',$config);
        $this->view('configs/listItem');
    }

	function detail($id = '', $return=true)
	{

		parent::detail($id); // TODO: Change the autogenerated stub
	}

}

//end of Config