<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class Menu extends Member_Controller {
	/**
	 * Model
	 * @var string
	 */
	public $model_name  = 'menu_model';
	/**
	 * 
	 * @var Menu_Model
	 */
	public $model;
	
	

	/**
	 * Menu controller 
	 */
	
	//form add
	protected $before_add = array();
	
	//form edit
	protected $before_edit = array();
	
	//action insert
	protected $before_insert = array();
	protected $after_insert = array();
	
	//action update
	protected $before_update = array();
	protected $after_update = array();
	
	//form view
	protected $before_view = array();	
	protected $after_view = array();
	
    public function __construct(){
        parent::__construct();  
        
    }

	public function add()
	{
		$aryCondition = $this->session->userdata(_getBaseName('getList.filter'));
		$this->template->set('menuType',$aryCondition['and'][0]['mt.menuType']);
		parent::add(); // TODO: Change the autogenerated stub
	}

	public function edit($id = '', $permission = 'all')
	{
		$aryCondition = $this->session->userdata(_getBaseName('getList.filter'));
		$this->template->set('menuType',$aryCondition['and'][0]['mt.menuType']);
		parent::edit($id, $permission); // TODO: Change the autogenerated stub
	}

	/**
	 * Build a Condition where for search 
	 * @return mixed:
	 * */	 
    protected function _buildCondition(){
    	$aryCondition = array();
    	
    	if(!empty($this->postData)){
    		 //sustomer code
			 			
			if($this->postData['moduleId']){
    		 	$aryCondition['and'][] =  array("moduleId"=>$this->postData['moduleId']);
    		 }			
			if($this->postData['menuName']){
    		 	$aryCondition['like'] =  array("menuName"=>$this->postData['menuName']);
    		 }
					
			if($this->postData['menuType']){
    		 	$aryCondition['and'][] =  array("menuType"=>$this->postData['menuType']);
    		 }			
			if($this->postData['status']!=''){
    		 	$aryCondition['and'][] =  array("mt.status"=>$this->postData['status']);
    		 }

    		if($this->postData['type']!=''){
    			$aryCondition['and'][] =  array("mt.menuType"=>$this->postData['type']);
    		}
			
    	}
    	return $aryCondition;
    }
    
    
	/**
	 * Get data for List screen
	 * @param array $aryCondition
	 * @param int $start
	 * @return mixed
	 */
    protected function _getDataList($aryCondition=array(),$start='',$sort=array()){
    	$rows = parent::_getDataList($aryCondition,$start,$sort,array('select'=>'mt.*','created'=>true));
    	return $rows;
    }
	
 
}

//end of Menu