<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class Position extends Member_Controller {
	/**
	 * Model
	 * @var string
	 */
	public $model_name  = 'position_model';
	/**
	 * 
	 * @var Position_Model
	 */
	public $model;
	
	

	/**
	 * Position controller 
	 */
	
	//form add
	protected $before_add = array();
	
	//form edit
	protected $before_edit = array();
	protected $after_edit = array();
	
	//action insert
	protected $before_insert = array();
	protected $after_insert = array();
	
	//action update
	protected $before_update = array();
	protected $after_update = array();
	
	//form view
	protected $before_view = array();	
	protected $after_view = array();
	
    public function __construct(){
        parent::__construct();  
        
    }

	public function index()
	{

		$page = $this->model->find_where('list',array(),array('select'=>'distinct page'));
		$aryPage = array();
		foreach($page as $p){
			$aryPage[$p->page] = $p->page;
		}
		$this->template->set('aryPage',$aryPage);
		return parent::index(); // TODO: Change the autogenerated stub
	}

	/**
	 * Build a Condition where for search 
	 * @return mixed:
	*/
    protected function _buildCondition(){
    	$aryCondition = array();
    	
    	if(!empty($this->postData)){
    		 //search
			 			
			if($this->postData['title']!=''){
    		 	$aryCondition['like'][] =  array("mt.title"=>$this->postData['title']);
    		 }			
			if($this->postData['page']!=''){
    		 	$aryCondition['and'][] =  array("mt.page"=>$this->postData['page']);
    		 }			
			if($this->postData['code']!=''){
    		 	$aryCondition['like'][] =  array("mt.code"=>$this->postData['code']);
    		 }			
			if($this->postData['status']!=''){
    		 	$aryCondition['and'][] =  array("mt.status"=>$this->postData['status']);
    		 }			

    	}
    	return $aryCondition;
    }
    
    
	/**
	 * Get data for List screen
	 * @param array $aryCondition
	 * @param int $start
	 * @return mixed
	*/ 
    protected function _getDataList($aryCondition=array(),$start='',$sort= array()){
    	return  parent::_getDataList($aryCondition,$start,$sort,array('select'=>'mt.*','created'=>true));
    	
    }
	
 
}

//end of Position